title: Temesgen Abera
logo: /assets/img/temu1.png
description: text below image
show_downloads: true
social_links:
  - name: Twitter
    url: https://twitter.com/yourusername
  - name: LinkedIn
    url: https://linkedin.com/in/yourusername
  - name: GitHub
    url: https://github.com/yourusername

theme: jekyll-theme-minimal
