title: Temesgen Abera Asfaw
logo: /assets/img/temu1.png
show_downloads: true
social_links:
  - name: Twitter
    url: https://twitter.com/yourusername
  - name: LinkedIn
    url: https://linkedin.com/in/yourusername
  - name: GitHub
    url: https://github.com/yourusername

theme: jekyll-theme-minimal
