title:  Temesgen Abera
logo: /assets/img/temu2.png
show_downloads: true
theme: jekyll-theme-minimal
description: You can download my CV from the following link: 
[Download CV](https://drive.google.com/uc?export=download&id=1a2b3c4d5e6f7g8h9i0j)

